name: finanzas_dashboard
description: "Un nuevo proyecto de Flutter para gestión financiera."
publish_to: "none" # Evita que subas el paquete a pub.dev por accidente

version: 1.0.0+1

environment:
  # Requiere una versión moderna de Dart
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS (Vienen por defecto)
  cupertino_icons: ^1.0.6

  # --- NUESTRAS DEPENDENCIAS ---
  # 1. Motor de estados para cambiar los temas (Azul, Verde, Gris)
  provider: ^6.1.2

  # 2. Motor de gráficos para la Dona (PieChart) del Panel Derecho
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de código limpio recomendadas por Google
  flutter_lints: ^3.0.0

flutter:
  # Habilita los componentes y el estilo de Material Design
  uses-material-design: true

  # Aquí es donde en el futuro agregarás tus tipografías o imágenes locales
  # assets:
  #   - assets/images/logo.png
